# deployment and service svc
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vernemq
spec:
  selector:
    matchLabels:
      app: vernemq
  template:
    metadata:
      labels:
        app: vernemq
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
      - name: vernemq
        image: vernemq/vernemq
        env:
          - name: DOCKER_VERNEMQ_ACCEPT_EULA
            value: "yes"
          - name: DOCKER_VERNEMQ_LISTENER__TCP__DEFAULT
            value: '0.0.0.0:1883'
          - name: DOCKER_VERNEMQ_LISTENER__WS__DEFAULT
            value: '0.0.0.0:8080'
          - name: DOCKER_VERNEMQ_LISTENER__HTTP__METRICS
            value: '0.0.0.0:8884'
          - name: DOCKER_VERNEMQ_LISTENER__VMQ__CLUSTERING
            value: '0.0.0.0:44053'
          - name: DOCKER_VERNEMQ_NODENAME
            value: 'vmq0.local2'
          - name: DOCKER_VERNEMQ_ALLOW_ANONYMOUS
            value: "on"
          - name: DOCKER_VERNEMQ_PLUGINS__VMQ_WEBHOOKS
            value: 'on'

          # webhook authenticate a connect using username, password
          - name: DOCKER_VERNEMQ_VMQ_WEBHOOKS__AUTH_ON_REG__HOOK
            value: 'auth_on_register'
          - name: DOCKER_VERNEMQ_VMQ_WEBHOOKS__AUTH_ON_REG__ENDPOINT
            value: 'http:///verne2promscale-service:8082/auth_on_register'

          # webhook publish
          - name: DOCKER_VERNEMQ_VMQ_WEBHOOKS__AUTH_ON_PUB__HOOK
            value: 'auth_on_publish'
          - name: DOCKER_VERNEMQ_VMQ_WEBHOOKS__AUTH_ON_PUB__ENDPOINT
            value: 'http:///verne2promscale-service:8082/auth_on_publish'
          - name: DOCKER_VERNEMQ_VMQ_WEBHOOKS__AUTH_ON_PUB__HOOK
            value: 'on_publish'
          - name: DOCKER_VERNEMQ_VMQ_WEBHOOKS__AUTH_ON_PUB__ENDPOINT
            value: 'http:///verne2promscale-service:8082/on_publish'


        ports:
          - name: mqtt
            containerPort: 1883
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-svc
spec:
  type: ClusterIP
  selector:
    app: vernemq
  ports:
    - name: mqtt
      port: 1883
      targetPort: mqtt

# https://github.com/vernemq/vernemq/issues/1421 <- macbook m1 issue
# https://github.com/vernemq/vernemq/issues/1714 <- example of docker configuration
