# IPS of the cluster elements
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 5432
        hostPort: 5432
      - containerPort: 9201
        hostPort: 9201
      - containerPort: 3000
        hostPort: 3000
      - containerPort: 1883
        hostPort: 1883
      - containerPort: 8082
        hostPort: 8082
